CREATE TABLE IF NOT EXISTS blog_categories (
  category_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar NOT NULL,
  slug varchar UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS blog_posts (
  post_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INT REFERENCES users(user_id),
  category_id INT REFERENCES blog_categories(category_id),
  title varchar NOT NULL,
  slug varchar UNIQUE NOT NULL,
  excerpt text DEFAULT '',
  content text DEFAULT '',
  cover_image varchar DEFAULT '',
  status varchar DEFAULT 'draft',
  reject_reason varchar DEFAULT '',
  published_at timestamp,
  created_at timestamp,
  updated_at timestamp
);

INSERT INTO blog_categories (name, slug) VALUES
  ('Tin tuc',    'tin-tuc'),
  ('Huong dan',  'huong-dan'),
  ('Xe dien',    'xe-dien'),
  ('Khuyen mai', 'khuyen-mai')
ON CONFLICT DO NOTHING;
