-- ===========================================
-- File: 001_schema.sql
-- ===========================================

-- GreenCar schema (PostgreSQL)
-- Chạy file này để tạo toàn bộ bảng và khóa ngoại.

CREATE TABLE "roles" (
  "role_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "role_name" varchar UNIQUE
);

CREATE TABLE "users" (
  "user_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "email" varchar UNIQUE,
  "password" varchar,
  "phone" varchar,
  "license_no" varchar,
  "role_id" int,
  "created_at" timestamp
);

CREATE TABLE "vehicle_models" (
  "vehicle_model_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "brand" varchar,
  "seats" int,
  "horsepower" int,
  "range_km" int,
  "trunk_capacity" int,
  "airbags" int,
  "vehicle_type" varchar,
  "transmission" varchar
);

CREATE TABLE "locations" (
  "location_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "address" varchar,
  "city" varchar,
  "latitude" decimal,
  "longitude" decimal
);

CREATE TABLE "vehicles" (
  "vehicle_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "vehicle_model_id" int,
  "license_plate" varchar UNIQUE,
  "status" varchar,
  "battery_level" int,
  "battery_health" int,
  "location_id" int
);

CREATE TABLE "vehicle_images" (
  "image_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "vehicle_model_id" int,
  "image_url" varchar
);

CREATE TABLE "rental_plans" (
  "rental_plan_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "duration_type" varchar,
  "max_km" int,
  "overtime_price" decimal,
  "over_km_price" decimal
);

CREATE TABLE "pricing" (
  "pricing_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "vehicle_model_id" int,
  "rental_plan_id" int,
  "price" decimal
);

CREATE TABLE "bookings" (
  "booking_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "vehicle_id" int,
  "rental_plan_id" int,
  "start_time" timestamp,
  "end_time" timestamp,
  "actual_start_time" timestamp,
  "actual_end_time" timestamp,
  "planned_km" int,
  "actual_km" int,
  "deposit_amount" decimal,
  "overtime_fee" decimal,
  "over_km_fee" decimal,
  "extra_fee" decimal,
  "extra_fee_description" text,
  "total_price" decimal,
  "status" varchar,
  "payment_method" varchar(20),
  "owner_note" text,
  "created_at" timestamp
);

CREATE TABLE "payments" (
  "payment_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "booking_id" int,
  "amount" decimal,
  "payment_method" varchar,
  "payment_status" varchar,
  "paid_at" timestamp
);

CREATE TABLE "reviews" (
  "review_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "vehicle_model_id" int,
  "booking_id" int UNIQUE,
  "rating" int,
  "comment" text,
  "created_at" timestamp
);

CREATE TABLE "vehicle_features" (
  "feature_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "feature_name" varchar
);

CREATE TABLE "vehicle_model_features" (
  "vehicle_model_id" int,
  "feature_id" int
);

CREATE TABLE "vehicle_specs" (
  "spec_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "vehicle_model_id" int,
  "spec_name" varchar,
  "spec_value" varchar
);

-- Foreign keys (thứ tự theo dependency)
ALTER TABLE "users" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("role_id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "vehicles" ADD FOREIGN KEY ("vehicle_model_id") REFERENCES "vehicle_models" ("vehicle_model_id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "vehicles" ADD FOREIGN KEY ("location_id") REFERENCES "locations" ("location_id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "vehicle_images" ADD FOREIGN KEY ("vehicle_model_id") REFERENCES "vehicle_models" ("vehicle_model_id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "pricing" ADD FOREIGN KEY ("vehicle_model_id") REFERENCES "vehicle_models" ("vehicle_model_id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "pricing" ADD FOREIGN KEY ("rental_plan_id") REFERENCES "rental_plans" ("rental_plan_id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "bookings" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "bookings" ADD FOREIGN KEY ("vehicle_id") REFERENCES "vehicles" ("vehicle_id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "bookings" ADD FOREIGN KEY ("rental_plan_id") REFERENCES "rental_plans" ("rental_plan_id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "payments" ADD FOREIGN KEY ("booking_id") REFERENCES "bookings" ("booking_id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "vehicle_model_features" ADD FOREIGN KEY ("vehicle_model_id") REFERENCES "vehicle_models" ("vehicle_model_id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "vehicle_model_features" ADD FOREIGN KEY ("feature_id") REFERENCES "vehicle_features" ("feature_id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "vehicle_specs" ADD FOREIGN KEY ("vehicle_model_id") REFERENCES "vehicle_models" ("vehicle_model_id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "reviews" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "reviews" ADD FOREIGN KEY ("vehicle_model_id") REFERENCES "vehicle_models" ("vehicle_model_id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "reviews" ADD FOREIGN KEY ("booking_id") REFERENCES "bookings" ("booking_id") DEFERRABLE INITIALLY IMMEDIATE;


-- ===========================================
-- File: 002_migration_001.sql
-- ===========================================

-- =============================================================
--  GreenCar — Migration 001
--  Chạy SAU schema gốc (xe dien (1).sql)
--  psql -U <user> -d <dbname> -f migration_001.sql
-- =============================================================

BEGIN;

-- 1. Thêm owner_id vào vehicles (chủ xe của từng xe)
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS owner_id INT REFERENCES users(user_id);

-- 2. Thêm cccd vào users
ALTER TABLE users ADD COLUMN IF NOT EXISTS cccd VARCHAR;

-- 3. Thêm reviewer_name vào reviews (tên người review, lưu denormalized)
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS reviewer_name VARCHAR;

-- 4. Thêm note (lời nhắn) vào bookings
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS customer_note TEXT;

-- 5. Thêm delivery_type và delivery_address vào bookings
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS delivery_type VARCHAR DEFAULT 'self';
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS delivery_address TEXT;

-- 6. Bảng conversations (index cuộc trò chuyện theo booking)
CREATE TABLE IF NOT EXISTS conversations (
  conversation_id  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id       INT REFERENCES bookings(booking_id) UNIQUE,
  vehicle_id       INT REFERENCES vehicles(vehicle_id) ON DELETE CASCADE,
  customer_id      INT REFERENCES users(user_id),
  owner_id         INT REFERENCES users(user_id),
  last_message_at  TIMESTAMPTZ DEFAULT now(),
  created_at       TIMESTAMPTZ DEFAULT now()
);

-- 7. Bảng messages (tin nhắn trong chat)
CREATE TABLE IF NOT EXISTS messages (
  message_id      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id INT REFERENCES conversations(conversation_id) ON DELETE CASCADE,
  sender_id       INT REFERENCES users(user_id),
  content         TEXT NOT NULL,
  is_read         BOOLEAN DEFAULT FALSE,
  created_at      TIMESTAMPTZ DEFAULT now()
);

-- Index để query nhanh tin nhắn theo conversation
CREATE INDEX IF NOT EXISTS idx_messages_conversation_id ON messages(conversation_id);
CREATE INDEX IF NOT EXISTS idx_messages_sender_id ON messages(sender_id);
CREATE INDEX IF NOT EXISTS idx_conversations_customer_id ON conversations(customer_id);
CREATE INDEX IF NOT EXISTS idx_conversations_owner_id ON conversations(owner_id);

COMMIT;


-- ===========================================
-- File: 003_posts.sql
-- ===========================================

CREATE TABLE IF NOT EXISTS posts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    author_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_posts_author_id ON posts(author_id);
CREATE INDEX idx_posts_created_at ON posts(created_at DESC);


-- ===========================================
-- File: 004_blog.sql
-- ===========================================

CREATE TABLE IF NOT EXISTS blog_categories (
  category_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar NOT NULL,
  slug varchar UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS blog_posts (
  post_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INT REFERENCES users(user_id),
  category_id INT REFERENCES blog_categories(category_id),
  title varchar NOT NULL,
  slug varchar UNIQUE NOT NULL,
  excerpt text DEFAULT '',
  content text DEFAULT '',
  cover_image varchar DEFAULT '',
  status varchar DEFAULT 'draft',
  reject_reason varchar DEFAULT '',
  published_at timestamp,
  created_at timestamp,
  updated_at timestamp
);

INSERT INTO blog_categories (name, slug) VALUES
  ('Tin tuc',    'tin-tuc'),
  ('Huong dan',  'huong-dan'),
  ('Xe dien',    'xe-dien'),
  ('Khuyen mai', 'khuyen-mai')
ON CONFLICT DO NOTHING;


-- ===========================================
-- File: 005_notifications.sql
-- ===========================================

-- Migration: 005_notifications.sql
-- Description: Create notifications table for the platform

CREATE TABLE IF NOT EXISTS notifications (
    notification_id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    type VARCHAR(50) NOT NULL,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    link VARCHAR(255),
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_notifications_user_id ON notifications(user_id);


-- ===========================================
-- File: 006_password_resets.sql
-- ===========================================

-- password_resets table

CREATE TABLE IF NOT EXISTS conversations (
    id SERIAL PRIMARY KEY,
    owner_id INT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    customer_id INT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    booking_id INT REFERENCES bookings(booking_id) ON DELETE SET NULL,
    vehicle_id INT REFERENCES vehicles(vehicle_id) ON DELETE CASCADE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS messages (
    id SERIAL PRIMARY KEY,
    conversation_id INT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    sender_id INT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    is_read BOOLEAN DEFAULT false,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS owner_registrations (
    id SERIAL PRIMARY KEY,
    user_id INT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    brand VARCHAR(255),
    model VARCHAR(255),
    year VARCHAR(50),
    license_plate VARCHAR(50) UNIQUE,
    color VARCHAR(50),
    seats VARCHAR(50),
    transmission VARCHAR(50),
    fuel_type VARCHAR(50),
    city VARCHAR(255),
    address TEXT,
    price_per_day DECIMAL,
    description TEXT,
    images JSONB,
    status VARCHAR(50) DEFAULT 'pending',
    reject_reason TEXT,
    available_from VARCHAR(100),
    available_to VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS vehicle_unavailabilities (
    id SERIAL PRIMARY KEY,
    vehicle_id INT NOT NULL REFERENCES vehicles(vehicle_id) ON DELETE CASCADE,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NOT NULL,
    type VARCHAR(50) DEFAULT 'blocked',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_vehicle_unavailabilities_vehicle_id ON vehicle_unavailabilities(vehicle_id);

CREATE TABLE IF NOT EXISTS password_resets (
    id SERIAL PRIMARY KEY,
    user_id INT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    token_hash VARCHAR(255) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    used BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_password_resets_token_hash ON password_resets(token_hash);


-- ===========================================
-- File: 008_pricing_rules_approval.sql
-- ===========================================

-- Migration: Flexible Pricing Rules + Owner Approval Flow
-- Run this against your PostgreSQL database

-- 1. Pricing rules table for each vehicle
CREATE TABLE IF NOT EXISTS vehicle_pricing_rules (
    id              SERIAL PRIMARY KEY,
    vehicle_id      INT NOT NULL REFERENCES vehicles(vehicle_id) ON DELETE CASCADE,
    rule_type       VARCHAR(50) NOT NULL, -- 'weekend', 'multi_day'
    discount_percent NUMERIC(5,2) DEFAULT 0,  -- % giảm giá (dương = giảm, âm = tăng)
    extra_percent   NUMERIC(5,2) DEFAULT 0,   -- % tăng giá (cuối tuần)
    min_days        INT DEFAULT 0,            -- áp dụng từ bao nhiêu ngày (cho multi_day)
    is_active       BOOLEAN DEFAULT TRUE,
    created_at      TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Add owner_note to bookings for rejection reason
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS owner_note TEXT;

-- Example seed data (optional)
-- INSERT INTO vehicle_pricing_rules (vehicle_id, rule_type, extra_percent, min_days) VALUES (1, 'weekend', 15, 0);
-- INSERT INTO vehicle_pricing_rules (vehicle_id, rule_type, discount_percent, min_days) VALUES (1, 'multi_day', 10, 3);


-- ===========================================
-- File: 008_promo_dates.sql
-- ===========================================

-- Migration: Update Pricing Rules for Promotional Dates
-- Run this against your PostgreSQL database

ALTER TABLE vehicle_pricing_rules ADD COLUMN IF NOT EXISTS promo_start_date DATE;
ALTER TABLE vehicle_pricing_rules ADD COLUMN IF NOT EXISTS promo_end_date DATE;


-- ===========================================
-- File: 009_booking_constraints.sql
-- ===========================================

-- 007_booking_constraints.sql
-- Kích hoạt extension btree_gist để có thể so sánh dấu '=' cho cột số nguyên (vehicle_id) kết hợp với '&&' cho tsrange
CREATE EXTENSION IF NOT EXISTS btree_gist;

-- Thêm Exclude Constraint vào bảng bookings
ALTER TABLE bookings 
ADD CONSTRAINT exclude_overlapping_bookings
EXCLUDE USING gist (
    vehicle_id WITH =, 
    tsrange(start_time, end_time) WITH &&
)
WHERE (status != 'cancelled');

-- Performance optimization indexes
CREATE INDEX IF NOT EXISTS idx_bookings_vehicle_id ON bookings(vehicle_id);
CREATE INDEX IF NOT EXISTS idx_bookings_user_id ON bookings(user_id);
CREATE INDEX IF NOT EXISTS idx_vehicles_owner_id ON vehicles(owner_id);
CREATE INDEX IF NOT EXISTS idx_vehicles_vehicle_model_id ON vehicles(vehicle_model_id);
CREATE INDEX IF NOT EXISTS idx_reviews_vehicle_model_id ON reviews(vehicle_model_id);
CREATE INDEX IF NOT EXISTS idx_vehicle_images_vehicle_model_id ON vehicle_images(vehicle_model_id);
CREATE INDEX IF NOT EXISTS idx_pricing_vehicle_model_id ON pricing(vehicle_model_id);

-- License verification columns
ALTER TABLE users ADD COLUMN IF NOT EXISTS license_front_url VARCHAR;
ALTER TABLE users ADD COLUMN IF NOT EXISTS license_back_url VARCHAR;
ALTER TABLE users ADD COLUMN IF NOT EXISTS license_status VARCHAR DEFAULT 'unverified';
ALTER TABLE users ADD COLUMN IF NOT EXISTS license_reject_reason TEXT;

