-- =============================================================
--  GreenCar — Migration 001
--  Chạy SAU schema gốc (xe dien (1).sql)
--  psql -U <user> -d <dbname> -f migration_001.sql
-- =============================================================

BEGIN;

-- 1. Thêm owner_id vào vehicles (chủ xe của từng xe)
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS owner_id INT REFERENCES users(user_id);

-- 2. Thêm cccd vào users
ALTER TABLE users ADD COLUMN IF NOT EXISTS cccd VARCHAR;

-- 3. Thêm reviewer_name vào reviews (tên người review, lưu denormalized)
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS reviewer_name VARCHAR;

-- 4. Thêm note (lời nhắn) vào bookings
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS customer_note TEXT;

-- 5. Thêm delivery_type và delivery_address vào bookings
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS delivery_type VARCHAR DEFAULT 'self';
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS delivery_address TEXT;

-- 6. Bảng conversations (index cuộc trò chuyện theo booking)
CREATE TABLE IF NOT EXISTS conversations (
  conversation_id  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id       INT REFERENCES bookings(booking_id) UNIQUE,
  customer_id      INT REFERENCES users(user_id),
  owner_id         INT REFERENCES users(user_id),
  last_message_at  TIMESTAMPTZ DEFAULT now(),
  created_at       TIMESTAMPTZ DEFAULT now()
);

-- 7. Bảng messages (tin nhắn trong chat)
CREATE TABLE IF NOT EXISTS messages (
  message_id      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id INT REFERENCES conversations(conversation_id) ON DELETE CASCADE,
  sender_id       INT REFERENCES users(user_id),
  content         TEXT NOT NULL,
  is_read         BOOLEAN DEFAULT FALSE,
  created_at      TIMESTAMPTZ DEFAULT now()
);

-- Index để query nhanh tin nhắn theo conversation
CREATE INDEX IF NOT EXISTS idx_messages_conversation_id ON messages(conversation_id);
CREATE INDEX IF NOT EXISTS idx_messages_sender_id ON messages(sender_id);
CREATE INDEX IF NOT EXISTS idx_conversations_customer_id ON conversations(customer_id);
CREATE INDEX IF NOT EXISTS idx_conversations_owner_id ON conversations(owner_id);

COMMIT;
