CREATE TABLE "roles" (
  "role_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "role_name" varchar UNIQUE
);

CREATE TABLE "users" (
  "user_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "email" varchar UNIQUE,
  "password" varchar,
  "phone" varchar,
  "license_no" varchar,
  "role_id" int,
  "created_at" timestamp
);

CREATE TABLE "vehicle_models" (
  "vehicle_model_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "brand" varchar,
  "seats" int,
  "horsepower" int,
  "range_km" int,
  "trunk_capacity" int,
  "airbags" int,
  "vehicle_type" varchar,
  "transmission" varchar
);

CREATE TABLE "vehicles" (
  "vehicle_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "vehicle_model_id" int,
  "license_plate" varchar UNIQUE,
  "status" varchar,
  "battery_level" int,
  "battery_health" int,
  "location_id" int
);

CREATE TABLE "locations" (
  "location_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "address" varchar,
  "city" varchar,
  "latitude" decimal,
  "longitude" decimal
);

CREATE TABLE "vehicle_images" (
  "image_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "vehicle_model_id" int,
  "image_url" varchar
);

CREATE TABLE "rental_plans" (
  "rental_plan_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "duration_type" varchar,
  "max_km" int,
  "overtime_price" decimal,
  "over_km_price" decimal
);

CREATE TABLE "pricing" (
  "pricing_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "vehicle_model_id" int,
  "rental_plan_id" int,
  "price" decimal
);

CREATE TABLE "bookings" (
  "booking_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "vehicle_id" int,
  "rental_plan_id" int,
  "start_time" timestamptz,
  "end_time" timestamptz,
  "actual_start_time" timestamptz,
  "actual_end_time" timestamptz,
  "planned_km" int,
  "actual_km" int,
  "deposit_amount" decimal,
  "overtime_fee" decimal,
  "over_km_fee" decimal,
  "total_price" decimal,
  "status" varchar,
  "created_at" timestamptz
);

CREATE TABLE "payments" (
  "payment_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "booking_id" int,
  "amount" decimal,
  "payment_method" varchar,
  "payment_status" varchar,
  "paid_at" timestamptz
);

CREATE TABLE "reviews" (
  "review_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "vehicle_model_id" int,
  "booking_id" int UNIQUE,
  "rating" int,
  "comment" text,
  "created_at" timestamptz
);

CREATE TABLE "vehicle_features" (
  "feature_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "feature_name" varchar
);

CREATE TABLE "vehicle_model_features" (
  "vehicle_model_id" int,
  "feature_id" int
);

CREATE TABLE "vehicle_specs" (
  "spec_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "vehicle_model_id" int,
  "spec_name" varchar,
  "spec_value" varchar
);

ALTER TABLE "users" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("role_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "vehicles" ADD FOREIGN KEY ("vehicle_model_id") REFERENCES "vehicle_models" ("vehicle_model_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "vehicles" ADD FOREIGN KEY ("location_id") REFERENCES "locations" ("location_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "vehicle_images" ADD FOREIGN KEY ("vehicle_model_id") REFERENCES "vehicle_models" ("vehicle_model_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "pricing" ADD FOREIGN KEY ("vehicle_model_id") REFERENCES "vehicle_models" ("vehicle_model_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "pricing" ADD FOREIGN KEY ("rental_plan_id") REFERENCES "rental_plans" ("rental_plan_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "bookings" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "bookings" ADD FOREIGN KEY ("vehicle_id") REFERENCES "vehicles" ("vehicle_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "bookings" ADD FOREIGN KEY ("rental_plan_id") REFERENCES "rental_plans" ("rental_plan_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "payments" ADD FOREIGN KEY ("booking_id") REFERENCES "bookings" ("booking_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "vehicle_model_features" ADD FOREIGN KEY ("vehicle_model_id") REFERENCES "vehicle_models" ("vehicle_model_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "vehicle_model_features" ADD FOREIGN KEY ("feature_id") REFERENCES "vehicle_features" ("feature_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "vehicle_specs" ADD FOREIGN KEY ("vehicle_model_id") REFERENCES "vehicle_models" ("vehicle_model_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "reviews" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "reviews" ADD FOREIGN KEY ("vehicle_model_id") REFERENCES "vehicle_models" ("vehicle_model_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "reviews" ADD FOREIGN KEY ("booking_id") REFERENCES "bookings" ("booking_id") DEFERRABLE INITIALLY IMMEDIATE;

-- ── BLOG ──────────────────────────────────────────────────────────────────────

CREATE TABLE "blog_categories" (
  "category_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name"        varchar NOT NULL,
  "slug"        varchar UNIQUE NOT NULL
);

CREATE TABLE "blog_posts" (
  "post_id"       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id"       int         NOT NULL,
  "category_id"   int,
  "title"         varchar     NOT NULL,
  "slug"          varchar UNIQUE NOT NULL,
  "excerpt"       text,
  "content"       text,
  "cover_image"   varchar,
  "status"        varchar     NOT NULL DEFAULT 'draft',
  -- status: draft | pending | published | rejected
  "reject_reason" text,
  "published_at"  timestamptz,
  "created_at"    timestamptz NOT NULL DEFAULT now(),
  "updated_at"    timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE "blog_posts" ADD FOREIGN KEY ("user_id")     REFERENCES "users"            ("user_id")     DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "blog_posts" ADD FOREIGN KEY ("category_id") REFERENCES "blog_categories"  ("category_id") DEFERRABLE INITIALLY IMMEDIATE;
